name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'  # Palitan kung ibang version gamit mo

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --split-per-abi

      - name: Show Build Output
        run: ls -R build/app/outputs/flutter-apk/

      - name: Upload APK
        uses: actions/upload-artifact@v4  # <-- UPDATED TO v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/*.apk
